version: '2.1'

services:
  api:
    build: ./api
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/srv/app/api/src
    command: npm run start
    
  client:
    build: ./client
    ports:
      - 3001:3001
    volumes:
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    links: 
      - api
    stdin_open: true
    command: npm run start
