version: '2.1'

services:
  api:
    build: ./api
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/srv/app/api/src
    command: npm run start
    
  client:
    build: ./front
    environment: 
      - REACT_APP_PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./front/src:/srv/app/front/src
      - ./front/public:/srv/app/front/public
    links: 
      - api
    stdin_open: true
    command: npm run start
